name: Weather Scraping

on:
  schedule:
    - cron: '*/5 * * * *' #'0 12 * * *' # run every day at 12pm UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install requirements
      run: pip install -r requirements.txt
      
    - name: Run notebook
      run: jupyter nbconvert --execute --to notebook --inplace Weather_web_scraper.ipynb
